class Team:
    def __init__(self, data):
        self.team: int = data.get('team')
        self.name: str = data.get('name')
        self.offseason: bool = data.get('offseason')
        self.state: str = data.get('state')
        self.country: str = data.get('country')
        self.district: str = data.get('district')
        self.rookie_year: int = data.get('rookie_year')
        self.active: bool = data.get('active')
        self.norm_epa: float = data.get('norm_epa')
        self.norm_epa_recent: float = data.get('norm_epa_recent')
        self.norm_epa_mean: float = data.get('norm_epa_mean')
        self.norm_epa_max: float = data.get('norm_epa_max')
        self.wins: int = data.get('wins')
        self.losses: int = data.get('losses')
        self.ties: int = data.get('ties')
        self.count: int = data.get('count')
        self.winrate: float = data.get('winrate')
        self.full_wins: int = data.get('full_wins')
        self.full_losses: int = data.get('full_losses')
        self.full_ties: int = data.get('full_ties')
        self.full_count: int = data.get('full_count')
        self.full_winrate: float = data.get('full_winrate')
